# The URL the site will be built for
base_url = "https://esliwka.github.io/ElimWeb/"
title = "ElimWeb"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
header_nav = [
  { url = "/ElimWeb", name = "/home/" },
  { url = "/ElimWeb/about", name = "/about/" },
  { url = "/ElimWeb/rafb", name = "/rafb/" },
  { url = "/ElimWeb/ramblings", name = "/ramblings/" },
  { url = "/ElimWeb/pics", name = "/pics/" },
]
